### ISSUE TITLE
Nom des régions

### ISSUE THREAD

**Issue by taniki** [nsppolls/nsppolls#1]
En effectuant, un recollement entre les fichiers du ministère de l'intérieur et ceux de nsppolls, j'ai remarqué quelques petites différences de graphie dans les noms de région :

```
minint[minint.indexOf("Grand Est")] = 'Grand-Est'
minint[minint.indexOf("Centre-Val de Loire")] = 'Centre-Val-de-Loire'
minint[minint.indexOf("Pays de la Loire")] = 'Pays-de-la-Loire'
```

**Comment by alphoenix** [comment]
Merci ! J'ai changé les noms pour plus de facilités ;)
