### ISSUE TITLE
[QoL] lister les commanditaires par virgules, sans "ET"

### ISSUE THREAD

**Issue by Guillaume-Levrier** [nsppolls/nsppolls#10]
Actuel : 
`commanditaire:  "Le Monde, le Cevipof et Fondation Jean Jaurès"`
Solution : 
`commanditaire:  "Le Monde, Cevipof, Fondation Jean Jaurès"`

Raison : ça permet d'obtenir des arrays avec array[x].commanditaire.split("s") et de remapper en conséquence.

C'est fixable en post faisant une regex qui cherche " et " et qui remplace par une virgule, mais ça serait plus simple de l'avoir en natif, et ça ne cassera pas les systèmes en production.

**Comment by alphoenix** [comment]
Ca sera corrigé dans le prochain commit ! Merci de votre intérêt !
