### ISSUE TITLE
[data] uniformiser les noms

### ISSUE THREAD

**Issue by Guillaume-Levrier** [nsppolls/nsppolls#11]
Un sondage est encodé comme "Le Monde, le Cevipof et Fondation Jean Jaurès", un autre comme ""Le Monde, Cevipof et Fondation Jean Jaurès". Nous avons coutume d'utiliser "le" CEVIPOF (c'est un ancien acronyme qui a été gardé comme marque, mais qui du coup, il me semble, garde ses majuscules).

**Comment by alphoenix** [comment]
J'ai mis Cevipof ! Mais le même partout
