### ISSUE TITLE
Ajout d'un indicateur sur le type de commanditaire

### ISSUE THREAD

**Issue by mthlht** [nsppolls/nsppolls#21]
Ne pensez-vous pas que ce serait intéressant d'ajouter une variable sur la typologie du commanditaire : MEDIAS / PARTI POLITIQUE / ORGANISATIONS SYNDICALE / GROUPE D'INTÉRÊT / AUTRE

**Comment by alphoenix** [comment]
Salut, je pense qu'une telle variable est compliquée : les commanditaires sont parfois de différents niveaux (SFR et l'Express dans le dernier sondage Elabe par exemple, est-ce qu'on le traite en média, "média, autre", etc.) et les réutilisateurs pourraient vouloir les classer différemment... Je pense que le plus simple est que tu le fasses de ton côté sans que le fichier ne "l'impose".
