### ISSUE TITLE
Erreur de reporting

### ISSUE THREAD

**Issue by bzkhv** [nsppolls/nsppolls#22]
Ligne 1329 du JSON présidentielles, remplacer Xavier Bertrand par Valérie Pécresse - le nom des candidats est incohérent avec le nom de l'hypothèse.

Merci pour votre travail !

PS : très peu familier de Github donc je ne sais pas si c'est le "bon moyen" de soulever le problème.

**Comment by alphoenix** [comment]
Merci ! C'est corrigé. 
C'est un très bon moyen, vous pouvez aussi par mail (contact@nsppolls.fr) ou en proposant directement un fichier modifié (niveau un peu plus expert en Github)
