### ISSUE TITLE
Faute d'orthographe nom candidat

### ISSUE THREAD

**Issue by fouronnes** [nsppolls/nsppolls#28]
Dans le fichier `presidentielle.json`, il y a une faute d'orthographe à un nom. `Eric Zemmour` alors que l'orthographe correcte semble être  `Éric Zemmour` (source: https://en.wikipedia.org/wiki/%C3%89ric_Zemmour).

En interne, je corrige le problème à l'import des données avec une réécriture systématique. C'est un choix technique de ne pas accentuer les majuscules ? Est-ce qu'on a la garantie qu'il n'y aura jamais de majuscule à ce nom et que la version sans accent identifie de manière unique ce candidat ? Et que du coup la présence de la version accentuée si elle avait lieu serait une erreur ? Si c'est le cas, ça vaut le coup de documenter ça quelque part, car il est possible que si l'ambiguïté se glisse dans le fichier par la suite, cela devienne une source d'erreur.

**Comment by alphoenix** [comment]
Salut, c'est une convention d'écriture que d'accentuer ou non les majuscules, j'ai choisi de ne pas le faire, notamment pour éviter de mettre éric ou eric, ne sachant pas laquelle était la bonne, mais aussi parce que c'est une convention en cours dans de nombreux médias. J'imagine qu'il est trop tard pour le modifier désormais, mais je peux garantir qu'il ne changera pas, les noms sont désormais normés et seuls les noms actuels sont possibles.
