### ISSUE TITLE
Normalisation du champ parti

### ISSUE THREAD

**Issue by nmondon** [nsppolls/nsppolls#3]
Hello, je suis en train d'ajouter une couche typescript pour faire des charts basés sur les données (je pourrais faire une PR  pour ajouter un fichier d.ts dans le repository au besoin). 

Du coup, j'avoue être un peu chagriné par la gestion du champ `parti`, qui peut être une string, un littéral vide ou une liste de string. 

Est-il envisageable de normaliser ce champ pour n'en faire qu'un tableau de string : 

 + {} => []
 + 'parti' => ['parti']
 + ['parti1', 'parti2'] ne change pas

```typescript
type Candidat = {
    candidat: string;
    parti: string | Array<string> | {};
    intentions: number;
    erreur_sup: number;
    erreur_inf: number;
};

type Hypothese = {
    hypothese: null | string;
    sous_echantillon: string;
    candidats: Array<Candidat>;
};

type Tour = {
    tour: 'Premier tour' | 'Second tour';
    hypotheses: Array<Hypothese>;
};

type Poll = {
    id: string;
    nom_institut: string;
    debut_enquete: string;
    fin_enquete: string;
    commanditaire: string;
    lien: string;
    echantillon: number;
    population: string;
    tours: Array<Tour>;
};

type Polls = Array<Poll>;

```

**Comment by nmondon** [comment]
```js
function normalizeParti(legacyParti){
  if(typeof legacyParty === "string"){
    return [legacyParti];
  }
  if(Array.isArray(legacyParti)){
    return legacyParti;
  }
  return [];
}
```

**Comment by alphoenix** [comment]
J'ai essayé de trouver une solution, mais je n'ai pas encore réussi. Pour l'instant, je génère le JSON à partir de plusieurs tables Airtable que je fusionne grâce à un petit script en R. Et le champ parti est géré comme une liste de liste, ou un élément vide. C'est galère de gérer les columns-lists en R, et la conversion en JSON n'est pas autant paramétrable que je le souhaiterais. Mais je vais trouver une solution.

**Comment by alphoenix** [comment]
Normalement, j'ai modifié le JSON pour que tous les champs partis soient sous la forme, dis-moi si ça fonctionne bien :

- ["nom_du_parti"] pour un seul parti,
- ["nom_parti_1","nom_parti_2"] pour plusieurs partis,
- [""] si vide
