### ISSUE TITLE
Baromètre politique

### ISSUE THREAD

**Issue by Ipuch** [nsppolls/nsppolls#33]
Bonjour,

Je suis membre de l'association Mieux voter, nous avons agrégé des données de sondages issus du [baromètre politique de Elabe](https://elabe.fr/tag/barometre-politique/) qui pourraient vous intéresser dans le cadre du suivi de l'opinion pour l'election présidentielle. 

Les sondés accordent chaque semaine une mention aux politiques de positive à negative. Nous avons retenu les donneés uniquement pour les candidats à l'election présidentielle, et transformer ces données pour qu'elles nous donnent le résultat qui correspond à un scrutin au jugement majoritaire (connu pour mieux correspondre à l'avis globale des électeurs).

Un exemple [ici](https://twitter.com/mieux_voter/status/1450044909780615168)

Il y a aussi cette [enquete](https://mieuxvoter.fr/index.php/2021/12/14/etude-sur-le-jugement-majoritaire/) commandée par mieux voter qui sonde directement des intentions de vote au jugement majoritaire.

Sachant qu'Elabe publie une étude par mois et que d'autres enquetes Opinion Way devraient venir. Je pense que ces données sont d'intérêt général et permettent d'avoir une vraie photographie de l'opinion des électeurs (sans évidement prédire le résultat du premier tour des élections...)

Est-ce qu'il y aurait une façon de pouvoir contribuer au dépôt en ajoutant les résultats de ces enquêtes de manière intelligente au dépôt ?

Bonne soirée.

**Comment by alphoenix** [comment]
Bonjour, 
Merci pour votre message et votre proposition de contribution. Concernant le travail fait sur Elabe, je ne pense pas qu'il soit possible de le reprendre sur ce fil, la question posée pour établir le classement n'a pas à voir avec l'élection présidentielle, et même si les résultats sont intéressants, il serait trompeur de faire comme si. Les enquêtes Opinion Way correspondent un peu plus à l'idée, et on pourrait envisager d'en faire un flux si elles venaient à se reproduire. L'objectif du repo est avant tout de proposer des informations fiables et réutilisables autour des intentions de vote pour l'élection présidentielle. Je reste disponible pour en parler quoi qu'il arrive.

**Comment by Ipuch** [comment]
Bonjour,

Merci pour votre réponse rapide. Je comprends votre angle de vue concernant les enquêtes Elabe. Cette proposition vient aussi du fait que l'on manque d'enquête au jugement majoritaire pour agréger un volume de données intéressantes. L'unique biais étant que la question n'est pas tournée vers l'election présentielle. Le traitement des données se prete parfaitement au JM.

Concernant les enquêtes Opinion Way seulement 2 supplémentaires ont été commandées à ma connaissance par Mieux Voter. Ainsi, elles se rapprochent de l'objectif du dépôt qui consiste à répondre: « Si le premier tour avait lieu dimanche, pour qui voteriez-vous ? », ou approchant.

En revanche, cette enquête au JM ne permet pas d'estimer des intentions de vote pour l'election présentielle mais plutôt des intentions de mention. Même si ces enquêtes témoignent plus de l'opinion des français, elle ne permettent pas de se faire une idée de ce qui va se passer au premier tour de l'election présidentielle. Je comprends donc que vous n'ayez qu'un intérêt modéré pour ces données. Par ailleurs, je ne connais pas d'autres enquêtes qui s'en rapproche.

Si vous êtes intéressés pour rappatrier quelques données, je suis disponible. Si ce n'est pas le cas vous pouvez fermer l'issue.
