### ISSUE TITLE
Reversed figures in April 18 Kantar poll

### ISSUE THREAD

**Issue by martinstabe** [nsppolls/nsppolls#41]
Macron and Le Pen headline values are reversed here:
https://github.com/nsppolls/nsppolls/commit/ec4c2477c983fded32fcf2290b4eab130dc38e0f#diff-c4df0b3355060c65697b0a488bd692ba32676375c14212f10afff410388cf7b0R8807-R8808

Source:
https://kantarpublic.com/fr/inspiration/election-presidentielle-2022/presidentielle-2022-emmanuel-macron-devance-marine-le-pen-dans-la-perspective-du-2nd-tour

**Comment by alphoenix** [comment]
Merci ! It has been corrected
