### ISSUE TITLE
Candidat PS dissident en Haute-Garonne 

### ISSUE THREAD

**Issue by nmondon** [nsppolls/nsppolls#47]
Hello, dans la circo 031-10, Simon Viguier devrait être candidat dissident. Je ne sais pas comment marche le système d'id, aussi je n'amende pas le fichier. 

- homme
- https://www.ladepeche.fr/2022/05/10/info-la-depeche-legislatives-en-haute-garonne-un-candidat-socialiste-dissident-face-a-lunion-de-la-gauche-10286216.php
- twitter : https://twitter.com/simonviguer

```csv
id,prenom,nom,sexe,sortante,circonscription,parti,lien,twitter
,Simon,Viguier,homme,,031-10,PS,https://www.ladepeche.fr/2022/05/10/info-la-depeche-legislatives-en-haute-garonne-un-candidat-socialiste-dissident-face-a-lunion-de-la-gauche-10286216.php,https://twitter.com/simonviguer
```

**Comment by alphoenix** [comment]
Ok, je regarde s'il se maintient, je n'ai pas vu de confirmation ailleurs et il dément dans le papier

**Comment by nmondon** [comment]
OK. Je ne sais pas si ça fait office de preuve mais c'est écrit dans sa bio twitter 💁

**Comment by alphoenix** [comment]
https://twitter.com/SimonViguer/status/1524683829293813760 ;)
