### ISSUE TITLE
Suppression de Loïc Minery

### ISSUE THREAD

**Issue by nmondon** [nsppolls/nsppolls#48]
https://www.lalsace.fr/elections/2022/05/10/loic-minery-doit-ceder-la-place-a-nadia-el-hajjaji-dans-la-5e-circonscription-du-haut-rhin

Il y a deux candidats NUPES dans la 068-05. A priori, c'est Loïc Minery qui passe à la trappe.

**Comment by alphoenix** [comment]
Merci !
