### ISSUE TITLE
Erreur de saisie dans un sondage second tour

### ISSUE THREAD

**Issue by nmondon** [nsppolls/nsppolls#6]
Hello, 

Je finalise l'agrégateur de sondages du Figaro et j'ai détecté une erreur de saisie dans un des sondages sur le second tour. 
Il s'agit du sondage **20210127_ips**. Les données de [la notice](http://www.commission-des-sondages.fr/notices/files/notices/2021/fevrier/9095-pres-ipsos-l-obs.pdf) donnent **56** pour Marcon et **44** pour MLP. 

Je ne te fournis pas de fix car j'ignore quelle méthode tu utilises pour le calcul de la marge d'erreur.

```json
 {
        "tour": "Deuxième tour",
        "hypotheses": [
          {
            "hypothese": null,
            "sous_echantillon": 547.5,
            "candidats": [
              {
                "candidat": "Marine Le Pen",
                "parti": ["Rassemblement national"],
                "intentions": 27,
                "erreur_sup": 30.7188,
                "erreur_inf": 23.2812
              },
              {
                "candidat": "Emmanuel Macron",
                "parti": ["LRM"],
                "intentions": 41,
                "erreur_sup": 45.1199,
                "erreur_inf": 36.8801
              }
            ]
          }
        ]
      }

```

**Comment by alphoenix** [comment]
Merci, c'est corrigé ;)

**Comment by nmondon** [comment]
Merci. Est-ce qu'il est possible de générer le json en sortie pou qu'il soit raccord avec le fix ?

**Comment by nmondon** [comment]
Au temps pour moi, je viens de voir le changement !
