### ISSUE TITLE
legislatives.csv / petite erreur

### ISSUE THREAD

**Issue by mqu** [nsppolls/nsppolls#70]
message d'erreur à l'ouverture du fichier, ce qui empêche de disposer de la fonction de recherche :
```
We can make this file [beautiful and searchable](https://docs.github.com/articles/rendering-csv-and-tsv-data) if this error is corrected: It looks like row 2316 should actually have 10 columns, instead of 9. in line 2315.
```
cordialement, Marc.

**Comment by alphoenix** [comment]
Merci, c'est corrigé !

*--*
*Alexandre Léchenet*
alphoenix.net

m : ***@***.***
t : (+33)6 12 460 260
t : @alphoenix


Le sam. 21 mai 2022 à 09:25, Marc Quinton ***@***.***> a
écrit :

**Comment by alphoenix** [comment]
Merci, c'est corrigé !
